/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2024-01-08 16:12:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class forgotPassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset='utf-8'>\r\n");
      out.write("\t\t<meta name='viewport' content='width=device-width, initial-scale=1'>\r\n");
      out.write("\t\t<title>Forgot Password</title>\r\n");
      out.write("\t\t<link href='https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css' rel='stylesheet'>\r\n");
      out.write("\t\t<link href='' rel='stylesheet'>\r\n");
      out.write("\t\t<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>\r\n");
      out.write("\t\t\r\n");
      out.write("        <!--Favicon-->\r\n");
      out.write("\t\t<link rel=\"icon\" type=\"image/x-icon\" href=\"images/favicon.ico\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tbackground-position: center;\r\n");
      out.write("\t\t\tbackground-color: #eee;\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\tcolor: #505050;\r\n");
      out.write("\t\t\tfont-family: \"Rubik\", Helvetica, Arial, sans-serif;\r\n");
      out.write("\t\t\tfont-size: 14px;\r\n");
      out.write("\t\t\tfont-weight: normal;\r\n");
      out.write("\t\t\tline-height: 1.5;\r\n");
      out.write("\t\t\ttext-transform: none\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.forgot {\r\n");
      out.write("\t\t\tbackground-color: #fff;\r\n");
      out.write("\t\t\tpadding: 12px;\r\n");
      out.write("\t\t\tborder: 1px solid #dfdfdf\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.padding-bottom-3x {\r\n");
      out.write("\t\t\tpadding-bottom: 72px !important\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.card-footer {\r\n");
      out.write("\t\t\tbackground-color: #fff\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.btn {\r\n");
      out.write("\t\t\tfont-size: 13px\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.form-control:focus {\r\n");
      out.write("\t\t\tcolor: #495057;\r\n");
      out.write("\t\t\tbackground-color: #fff;\r\n");
      out.write("\t\t\tborder-color: #76b7e9;\r\n");
      out.write("\t\t\toutline: 0;\r\n");
      out.write("\t\t\tbox-shadow: 0 0 0 0px #28a745\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body oncontextmenu='return false' class='snippet-body'>\r\n");
      out.write("\t\t<div class=\"container padding-bottom-3x mb-2 mt-5\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-md-10\">\r\n");
      out.write("\t\t\t\t\t<div class=\"forgot\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Forgot your password?</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Change your password in three easy steps. This will help you\r\n");
      out.write("\t\t\t\t\t\t\tto secure your password!</p>\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"text-primary text-medium\">1. </span>Enter\r\n");
      out.write("\t\t\t\t\t\t\t\tyour email address below.</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"text-primary text-medium\">2. </span>Our\r\n");
      out.write("\t\t\t\t\t\t\t\tsystem will send you an OTP to your email</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"text-primary text-medium\">3. </span>Enter the OTP on the \r\n");
      out.write("\t\t\t\t\t\t\tnext page</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form class=\"card mt-4\" action=\"forgotPassword\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"email-for-pass\">Enter your email address</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" type=\"text\" name=\"email\" id=\"email-for-pass\" required=\"\"><small\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-text text-muted\">Enter the registered email address . Then we'll\r\n");
      out.write("\t\t\t\t\t\t\t\t\temail a OTP to this address.</small>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-success\" type=\"submit\">Get New\r\n");
      out.write("\t\t\t\t\t\t\t\tPassword</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-danger\" type=\"submit\">Back to\r\n");
      out.write("\t\t\t\t\t\t\t\tLogin</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js'></script>\r\n");
      out.write("\t\t<script type='text/javascript' src=''></script>\r\n");
      out.write("\t\t<script type='text/javascript' src=''></script>\r\n");
      out.write("\t\t<script type='text/Javascript'></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
