/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2024-01-08 21:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.greenmart.dao.*;
import com.greenmart.connection.*;
import com.greenmart.model.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.greenmart.model");
    _jspx_imports_packages.add("com.greenmart.dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.greenmart.connection");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	productDao pd = new productDao(dbCon.getConnection());
	List<ProductModel> products = pd.getAllProducts();
	
	UserModel auth = (UserModel) request.getSession().getAttribute("auth");
	if (auth != null){
		request.setAttribute("auth", auth);
	}
	
	ArrayList<CartModel> cart_list = (ArrayList<CartModel>) session.getAttribute("cart-list");
	if(cart_list != null){
		request.setAttribute("cart_list", cart_list);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"ISO-8859-1\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>GreenMart</title>\r\n");
      out.write("\r\n");
      out.write("        <!--Stylesheet-->\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("        <!--Favicon-->\r\n");
      out.write("\t\t<link rel=\"icon\" type=\"image/x-icon\" href=\"images/favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("        <script src = 'js/index.js' defer></script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <!--nav-->\r\n");
      out.write("        <nav class=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("            <!--logo-->\r\n");
      out.write("            <a href=\"#\" class=\"logo\">\r\n");
      out.write("                <span>Green</span>Mart\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!--menu-->\r\n");
      out.write("            <ul class=\"menu\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"index.jsp\" class=\"active\"> \r\n");
      out.write("                        Home\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"AboutUs.jsp\">\r\n");
      out.write("\t\t\t\t\t\tAbout&nbsp;us\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<a href=\"feedback.jsp\">\r\n");
      out.write("\t\t\t\t\t\tFeedback\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

				if (session.getAttribute("auth") != null){
      out.write("\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"logout\">\r\n");
      out.write("\t                        Logout\r\n");
      out.write("\t                    </a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("                    <a href=\"login.jsp\">\r\n");
      out.write("                        Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"signup.jsp\">\r\n");
      out.write("                        Sign&nbsp;Up\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("            <!--right-nav-(cart-like)-->\r\n");
      out.write("            <div class=\"right-nav\">\r\n");
      out.write("                <!--cart-->\r\n");
      out.write("                <a href=\"ShoppingCart.jsp\" class=\"cart\">\r\n");
      out.write("                    <i class=\"fa-solid fa-cart-shopping\">\r\n");
      out.write("                    \t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart_list.size() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                    </i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!--nav-end-->\r\n");
      out.write("\r\n");
      out.write("        <!--banner-->\r\n");
      out.write("        <section id=\"banner\">\r\n");
      out.write("\r\n");
      out.write("            <!--bg-->\r\n");
      out.write("            <img alt=\"bg\" class=\"bg-1\" src=\"images/banner.jpg\">\r\n");
      out.write("\r\n");
      out.write("            <!--text-->\r\n");
      out.write("            <div class=\"banner-text\">\r\n");
      out.write("                <h1>  \r\n");
      out.write("                    Order Your Daily Groceries <br>and Essential Needs\r\n");
      out.write("                </h1>\r\n");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                <h3 style=\"color: rgb(0, 0, 0); text-align: center;\" >\r\n");
      out.write("                    Your Fresh Choice for a Greener Life\r\n");
      out.write("                </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--main-banner-end-->\r\n");
      out.write("        \r\n");
      out.write("        <!--products-->\r\n");
      out.write("        <section id=\"product\">\r\n");
      out.write("            <!--heading-->\r\n");
      out.write("            <div class=\"product-heading\">\r\n");
      out.write("                <h3>Products</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!--box-container-->\r\n");
      out.write("            <div class=\"product-container\">\r\n");
      out.write("            ");

                	if(!products.isEmpty()){
                		for(ProductModel p:products){
      out.write("\r\n");
      out.write("                \t\t\t<div class=\"product-box\">\r\n");
      out.write("                            <img alt=\"");
      out.print( p.getName());
      out.write("\" src=\"");
      out.print( p.getImage() );
      out.write("\">\r\n");
      out.write("                            <strong>");
      out.print( p.getName() );
      out.write("</strong>\r\n");
      out.write("                            <span class=\"quantity\">");
      out.print( p.getSize() );
      out.write("</span>\r\n");
      out.write("                            <span class=\"price\">$");
      out.print( p.getPrice() );
      out.write("</span>\r\n");
      out.write("                            <!--cart-btn-->\r\n");
      out.write("                            <a href=\"add-to-cart?id=");
      out.print( p.getProductID() );
      out.write("\" class=\"cart-btn\">\r\n");
      out.write("                                Add to cart\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                \t\t");
}
                	}
            
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--products-end-->  \r\n");
      out.write("        \r\n");
      out.write("        <!--footer-->\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"footer-container\">\r\n");
      out.write("                <!--logo-container-->\r\n");
      out.write("                <div class=\"footer-logo\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span>Green</span>Mart\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!--social-->\r\n");
      out.write("                    <div class=\"footer-social\">\r\n");
      out.write("                        <img src =\"images/paypal.png\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"footer-links\">\r\n");
      out.write("                <strong>Contact</strong>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li style = \"color: white;\">Phone : +94 112 345 678</li>\r\n");
      out.write("                    <li style = \"color: white;\">Email : greenmart@gmail.com</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\t\t\t\t<br><p style=\"color: aliceblue;\">Copyright ©2023 | GreenMart All Rights Reserved</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!--footer-end-->\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
