/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2024-01-08 13:58:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.greenmart.dao.*;
import com.greenmart.connection.*;
import com.greenmart.model.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.greenmart.model");
    _jspx_imports_packages.add("com.greenmart.dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.greenmart.connection");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	UserModel auth = (UserModel) request.getSession().getAttribute("auth");
	if (auth != null){
		response.sendRedirect("index.jsp");
	}

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("\t\t<title>GreenMart Login</title>\n");
      out.write("\t\t\n");
      out.write("\t\t<!--Font-Icon-->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"fonts/material-icon/css/material-design-iconic-font.min.css\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t<!--Favicon-->\n");
      out.write("\t\t<link rel=\"icon\" type=\"image/x-icon\" href=\"images/favicon.ico\" />\n");
      out.write("\t\t\n");
      out.write("\t\t<!--Main-css-->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\n");
      out.write("\t\t<input type=\"hidden\" id=\"status\" value=\"");
      out.print( request.getAttribute("status") );
      out.write("\">\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"main\">\n");
      out.write("\t\n");
      out.write("\t\t\t<!--Sing-in-Form-->\n");
      out.write("\t\t\t<section class=\"sign-in\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"signin-content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"signin-image\">\n");
      out.write("\t\t\t\t\t\t\t<figure>\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.jsp\"><img src=\"images/Greenmart.png\" alt=\"sing up image\"></a>\n");
      out.write("\t\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"signup.jsp\" class=\"signup-image-link\">Create an\n");
      out.write("\t\t\t\t\t\t\t\taccount</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t<div class=\"signin-form\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"form-title\">Sign in</h2>\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"login\" class=\"register-form\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"login-form\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"email\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"zmdi zmdi-account material-icons-name\"></i></label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"email\" id=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Your Email\" required=\"required\"/>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"password\"><i class=\"zmdi zmdi-lock\"></i></label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"password\" id=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" required=\"required\"/>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"forgotPassword.jsp\">Forgot Password?</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group form-button\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"signin\" id=\"signin\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-submit\" value=\"Log in\" />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t\t<!--JS-->\n");
      out.write("\t\t<script src=\"vendor/jquery/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"js/main.js\"></script>\n");
      out.write("\t\t<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"alert/dist/sweetalert.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<script type = \"text/javascript\">\n");
      out.write("\t\t\tvar status = document.getElementById(\"status\").value;\n");
      out.write("\t\t\tif (status == \"Failed\"){\n");
      out.write("\t\t\t\tswal(\"Sorry\", \"Wrong email or password\", \"error\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse if (status == \"invalidEmail\"){\n");
      out.write("\t\t\t\tswal(\"Sorry\", \"Please enter email\", \"error\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse if (status == \"invalidPassword\"){\n");
      out.write("\t\t\t\tswal(\"Sorry\", \"Please enter password\", \"error\");\n");
      out.write("\t\t\t}else if (status == \"resetSuccess\"){\n");
      out.write("\t\t\t\tswal(\"Congratulations\", \"Password Reset Successful\", \"success\");\n");
      out.write("\t\t\t}else if (status == \"resetFailed\"){\n");
      out.write("\t\t\t\tswal(\"Sorry\", \"Password Reset Failed\", \"error\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
